# Generated by Django 2.1 on 2018-08-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='wallet',
            field=models.FloatField(default=0.0),
        ),
    ]
