# Generated by Django 2.1 on 2018-08-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180819_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='result',
            name='current_term',
            field=models.CharField(choices=[('first term', 'First Term'), ('second term', 'Second Term'), ('third term', 'Third Term')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='subject',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='accounts.School'),
        ),
    ]
