# Generated by Django 2.1 on 2018-08-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180822_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='result',
            name='logo',
            field=models.ImageField(upload_to='result/logo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='subject',
            table='Subjects',
        ),
    ]
