# Generated by Django 2.1 on 2018-08-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180827_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='current_session',
            field=models.CharField(default='aha', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='current_term',
            field=models.CharField(choices=[('first term', 'First Term'), ('second term', 'Second Term'), ('third term', 'Third Term')], default='first term', max_length=50),
        ),
    ]
