# Generated by Django 2.1 on 2018-09-05 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180830_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=100)),
                ('parent_phone', models.IntegerField()),
                ('passport', models.ImageField(upload_to='result/logo/%Y/%m/%d/')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='accounts.Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
