# Generated by Django 2.1 on 2018-09-05 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180905_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.School'),
            preserve_default=False,
        ),
    ]
