# Generated by Django 2.1 on 2018-09-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.ImageField(null=True, upload_to='student/passport/%Y/%m/%d/'),
        ),
    ]
