# Generated by Django 2.1 on 2018-09-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresultsheet',
            name='average',
            field=models.FloatField(),
        ),
    ]
