# Generated by Django 2.1 on 2018-10-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20180930_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubjectresult',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
